blank_issues_enabled: false
contact_links:
  - name: ğŸŒˆ ç¤¾åŒºäº¤æµ
    url: https://github.com/iAJue/MoeKoeMusic/discussions
    about: åŠ å…¥æˆ‘ä»¬çš„ç¤¾åŒºè¿›è¡Œäº¤æµå’Œè®¨è®º
  - name: ğŸ“š é¡¹ç›®æ–‡æ¡£
    url: https://music.moekoe.cn/
    about: æŸ¥çœ‹é¡¹ç›®æ–‡æ¡£ä»¥è·å–æ›´å¤šå¸®åŠ©ä¿¡æ¯
  - name: ğŸ› ï¸ å¼€å‘ä¸ç¼–è¯‘
    url: https://github.com/iAJue/MoeKoeMusic?tab=readme-ov-file#%EF%B8%8F-%E5%BC%80%E5%8F%91
    about: äº†è§£é¡¹ç›®å¦‚ä½•è¿›è¡Œå¼€å‘å’Œç¼–è¯‘
  - name: ğŸ¤ è´¡çŒ®æŒ‡å—
    url: https://github.com/iAJue/MoeKoeMusic/blob/main/CONTRIBUTING.md
    about: äº†è§£å¦‚ä½•ä¸ºé¡¹ç›®åšå‡ºè´¡çŒ®